credentials:
  location: credentials.json
project:
  id: gcloud-lab


spring:
  cloud:
    stream:
      bindings:
        input-usuario-criado:
          destination: usuario-criado
          group: erp-central-usuario-criado
          content-type: application/json
server:
  port: 8889

logging:
  level:
    org.springframework.cloud.stream.binder.pubsub: debug
    org.springframework.integration: debug